### ISSUE TITLE
Monitor stops publishing after 15-20 mins

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-mirror-node#1596]
**Detailed Description**
With subscribe section enabled in the application config file, the traffics will shutdown after running about 10-20 mins.

**Actual Behavior**
Here is a test configuration that was used to reproduce the scenario on both two performance networks(the network section and key are removed):

```
      operator:
        accountId: 0.0.1016
        privateKey: <key>
      publish:
        connections: 1000
        scenarios:
          - name: HTSTransferTOKEN
            duration: 110m
            properties:
              senderAccountId: 0.0.1016
              recipientAccountId: 0.0.1017
              tokenId: 0.0.1020
              amount: 1
              transferType: TOKEN
            warmupPeriod: 60s
            tps: 100
            type: CRYPTO_TRANSFER
      subscribe:
        enabled: true
        rest:
          - name: HTSTransferTOKENSub
            enabled: true
            samplePercent: 0.03

```
The issue was reproduced with 100 TPS and above(the higher the TPS, the shorter the traffic lasts), see attached graphs for tps 100, 200 and 500(grafana charts recorded by the client and on kibana board).  monitor log for the 100 tps test is also attached.

**Expected Behavior**
Traffic is expected to run at given  TPS level for the duration specified, 110 mins in the sample above running 100 TPS.

**Environment:**

gcr.io/mirrornode/hedera-mirror-monitor:0.27.0

![perf_500](https://user-images.githubusercontent.com/73138984/108644706-caf54780-7475-11eb-934f-c3937fd7b351.PNG)
![perf_100_kibana](https://user-images.githubusercontent.com/73138984/108644707-cb8dde00-7475-11eb-8143-9e9476ec2793.PNG)
![perf_100](https://user-images.githubusercontent.com/73138984/108644708-cb8dde00-7475-11eb-8735-893ba2e69500.PNG)
![perf_200_kibana](https://user-images.githubusercontent.com/73138984/108644709-cc267480-7475-11eb-9022-d3a7575d22bd.PNG)
![perf_200](https://user-images.githubusercontent.com/73138984/108644710-cc267480-7475-11eb-9848-07aa6f473b64.PNG)
![perf_500_kibana](https://user-images.githubusercontent.com/73138984/108644711-cc267480-7475-11eb-8e03-75c02698a9c8.PNG)
[perf_100.log](https://github.com/hashgraph/hedera-mirror-node/files/6018953/perf_100.log)
