### ISSUE TITLE
Unable to configure MirrorNode to pick transactions for a specific account id.

### ISSUE THREAD

**Issue by vshall20** [hashgraph/hedera-mirror-node#2108]
Please ask questions you have in our [Discord](https://discordapp.com/invite/FFb9YFX) group first. You can also search GitHub to see if the issue has been reported already.

Otherwise, please feel free to ask your question here.

**Application.yaml:**
```
hedera:
 mirror:
   importer:
     downloader:
       accessKey: ABCD
       cloudProvider: "GCP"
       gcpProjectId: project123
       secretKey: MySuperSecretKey
     network: MAINNET
     startDate: "2021-06-11T00:00:00.000000000Z"
     parser:
      include:
        entity: 
          - 0.0.8870
          # - 0.0.16001
        # transaction:
        #   - CRYPTOCREATEACCOUNT
        #   - CRYPTOTRANSFER
        #   - CONTRACTCREATEINSTANCE
        #   - FILECREATE
        #   - FILEAPPEND
        #   - FILEDELETE
        #   - FILEUPDATE
```
I am trying to fetch data from a given startDate, for a particular Account Id and for particular transaction types, which are commented for now.

But the REST API still returns all types of Transactions for all account Ids which it has collected.
Please let me know what is missing in this?

**Comment by vshall20** [comment]
I do not see the `data` folder created, only the `db` folder is created.

**Comment by xin-hedera** [comment]
The configuration doc is inconsistent with the implementation.

For now, to make it work, e.g., only include consesussubmitmessage transactions with topic id 0.0.1263, importer should be configured as follows:

```yaml
hedera:
  mirror:
    importer:      
      parser:
        include:
          - entity:
              - "0.0.123456"
            transaction:
              - CONSENSUSSUBMITMESSAGE
```

We will make update to address the issue.
