### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#344]
**Problem**
Right now releasing requires updating the versions in the `pom.xml` and `package.json`, committing, tagging and updating the versions again to a snapshot version. And this process doesn't include creating a GitHub release, adding release notes or updating a CHANGELOG.

**Solution**
- When a milestone is closed, it should trigger a workflow that does the following:
  - Using version from milestone, create and push a `release/0.x` from master if it does not exist
  - Checkout `release/0.x`
  - Update pom.xml `release.chartVersion` and `release.version`
  - Run `./mvnw clean package -N -P=release`
  - Run `helm dependency update charts/hedera-mirror`
  - Run `Decathlon/release-notes-generator-action` to generate release notes. It uses the same Spring's [github-changelog-generator](https://github.com/spring-io/github-changelog-generator) that we use now. Use below config for `.github/workflows/release-notes.yml` to match our current format:
```yaml
changelog:
  contributors:
    title: "Contributors"
  issues:
    exclude:
      labels: ["wontfix", "question", "duplicate", "invalid"]
  repository: hashgraph/hedera-mirror-node
  sections:
  - title: "Enhancements"
    labels: ["enhancement"]
  - title: "Bug Fixes"
    labels: ["bug"]
  - title: "Documentation"
    labels: ["documentation", "docs"]
  - title: "Dependency Upgrades"
    labels: ["dependency-upgrade", "dependencies"]
```
  - Prepend those release notes along with a date/version header to `CHANGELOG.md`
  - Commit and tag those changes using version from milestone (use `stefanzweifel/git-auto-commit-action`)
  - Create a draft GitHub release with release notes text. Can maybe prepend milestone description to release description. That would allow us to do the descriptive part of the release notes in the milestone and it get carried over.

As we will transition away from release artifacts when we move to Kubernetes, we don't need to spend cycles automatically uploading artifacts to release.

**Alternatives**

**Additional Context**
