### ISSUE TITLE
OpenAPI spec example missing nft allowance info

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#3756]
### Description

The example section of `/components/schemas/Nft` is missing nft allowance fields `delegating_spender_id` and `spender_id`:

```yml
      example:
        account_id: "0.1.2"
        created_timestamp: "1234567890.000000001"
        deleted: false
        metadata: "VGhpcyBpcyBhIHRlc3QgTkZU"
        modified_timestamp: "1610682445.003266001"
        serial_number: 124
        token_id: "0.0.222"
```

### Steps to reproduce

check the description and openapi.yml

### Hedera network

testnet

### Version

v0.56.0
