### ISSUE TITLE
Support configuration of web3 module contract call request data size limit

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#7692]
### Problem

Currently the mirror node hard codes the request data size limit supported by the `ContractController` in the web3 module
https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java#L41

This doesn't allow for local experimentation with tools that may go beyond this limit but also doesn't allow for Mirror Node operators to configure their limit higher or lower if so desired.

### Solution

Make this value configureable so that it can be modified without code change.

Potentially add a `hedera.mirror.web3.call.dataSizeLimit` or `hedera.mirror.web3.call.dataSizeLimit` (whatever is appropriate) that can be configured to set the desired limit.
Default can remain `24576 * 2` i.e. 24KiB

**Comment by Neurone** [comment]
Side note as a reminder: there's a related `maxLength` parameter to be updated accordingly to the `dataSizeLimit` in the [ContractCallRequest API definition](https://github.com/hashgraph/hedera-mirror-node/blob/32aec94915caeef5859eae216f5e3a3de708f782/hedera-mirror-rest/api/v1/openapi.yml#L2490):

```yml
...
ContractCallRequest:
  type: object
  properties:
    data:
      description: Hexadecimal method signature and encoded parameters.
      example: "0x47f1aae7"
      format: binary
      maxLength: 12288
      nullable: true
      pattern: "^(0x)?[0-9a-fA-F]+$"
      type: string
...
```
