### ISSUE TITLE
Chart Workflow Setup Kind Step Fails

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#7868]
### Problem

When the chart workflow executes, the setup kind step fails as it seems it is not able to successfully start the k8s components.

### Solution

release engineering mentioned there are issues present using various kind images. Update workflow step to configure kind as follows:
```
- name: Setup Kind
   uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
   if: ${{ inputs.enable-e2e-tests && !cancelled() && !failure() }}
   with:
     install_only: true
     node_image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
     version: v0.21.0
     kubectl_version: v1.28.6
     verbosity: 3
     wait: 120s
```
