### ISSUE TITLE
Home README needs Assumed Knowledge & PrerequisiteTool Install Requirements

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#790]
**Problem**
Current repo documentation assumes users have knowledge of things like postgres, docker and also have docker and other tools installed.
We don't call these out explicitly and should as users of varying technical abilities will need to ramp up and get going on mirror node.

**Solution**
Update README.md with
- Knowledge area - PostgresSql, docker commands, java spring configurations etc
- Prerequisite tools e.g. docker, open jdk, nodejs etc
- Update Dockerfile w version & version plugin to keep it updated. Then can remove the ./mvnw clean install
- Add note for if not using the demo-bucket please create an application.yaml file in desired sub project to customize run

**Alternatives**
Provide links to docs under /docs where the information is already stated

**Additional Context**
Documentation is being created on docs.hedera.com that users of many different technical capabilities will be looking at. They will reference the this repo and where possible utilize its instructions or add. As such we need to make sure we have clear concise steps to make ramp up quickly

If possible add easy commands for accessing importer data in database for "Accessing Mirror Node Data" section of docs.hedera.com documentation

**Comment by Nana-EC** [comment]
We discussed the default application.yaml file missing issue.
We decided on not adding it to main README.md as that's meant to be the smallest steps to get you up and running which right now means using the demo bucket.

However, I added a note in the task to at least explicitly call out that if not using a demo bucket you should create that file and uncomment Dockerfile sections to pick it up

**Comment by injectedfusion** [comment]
If we don't provide sample application.yml then we should at least provide how to build one in the README docs, something like this:
  
```
hedera:
  mirror:
    importer:
      downloader:
        bucketName: "{{bucket_name}}"
        cloudProvider: "{{cloud_provider}}"
        accessKey: "{{access_key}}"
        secretKey: "{{secret_key}}"
        gcpProjectId: "{{project_id}}"
      network: "{{network}}"
      topicRunningHashV2AddedTimestamp: "{{topic}}"
```

Additionally, we discovered that we need to insure that latest docker images are being pulled. [installation.md](https://github.com/hashgraph/hedera-mirror-node/blob/master/docs/installation.md) needs to look like this

`./mvnw install -DskipTests -Ddocker.tag.version=latest`
