### ISSUE TITLE
Investigate Node Failure On Citus Worker

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#8869]
### Description

Performance environment had a citus worker pod stuck in terminating. It appears that the underlying node was experiencing failures:
```
conditions:
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kernel has no deadlock
    reason: KernelHasNoDeadlock
    status: "False"
    type: KernelDeadlock
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not use v1alpha2 CRI'
    reason: DeprecatedUsingV1Alpha2CriNotDetected
    status: "False"
    type: DeprecatedUsingV1Alpha2Cri
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not find any deprecations other than 3 configs
      fields (auths/configs/mirrors), pulling schema v1 images and using v1alpha2
      CRI.'
    reason: DeprecatedOtherContainerdFeaturesNotDetected
    status: "False"
    type: DeprecatedOtherContainerdFeatures
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not pull any schema v1 images'
    reason: DeprecatedPullingSchemaV1ImageDetected
    status: "False"
    type: DeprecatedPullingSchemaV1Image
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kubelet is functioning properly
    reason: NoFrequentKubeletRestart
    status: "False"
    type: FrequentKubeletRestart
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not find any deprecated ''configs'' field in
      containerd''s config'
    reason: DeprecatedConfigsFieldInContainerdConfigurationNotDetected
    status: "False"
    type: DeprecatedConfigsFieldInContainerdConfiguration
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: docker is functioning properly
    reason: NoFrequentDockerRestart
    status: "False"
    type: FrequentDockerRestart
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: containerd is functioning properly
    reason: NoFrequentContainerdRestart
    status: "False"
    type: FrequentContainerdRestart
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: docker overlay2 is functioning properly
    reason: NoCorruptDockerOverlay2
    status: "False"
    type: CorruptDockerOverlay2
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: node is functioning properly
    reason: NoFrequentUnregisterNetDevice
    status: "False"
    type: FrequentUnregisterNetDevice
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not find any deprecated ''auths'' field in
      containerd''s config'
    reason: DeprecatedAuthsFieldInContainerdConfigurationNotDetected
    status: "False"
    type: DeprecatedAuthsFieldInContainerdConfiguration
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: 'No deprecation risk: did not find any deprecated ''mirrors'' field in
      containerd''s config'
    reason: DeprecatedMirrorsFieldInContainerdConfigurationNotDetected
    status: "False"
    type: DeprecatedMirrorsFieldInContainerdConfiguration
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: Filesystem is not read-only
    reason: FilesystemIsNotReadOnly
    status: "False"
    type: ReadonlyFilesystem
  - lastHeartbeatTime: "2024-07-24T23:05:20Z"
    lastTransitionTime: "2024-07-23T08:40:47Z"
    message: '{"unmanaged": {"kernel.spl.kmem.slab_kvmem_alloc": "52765440", "kernel.spl.kmem.slab_kvmem_max":
      "53814016", "kernel.spl.kmem.slab_kvmem_total": "61186880", "net.ipv4.conf.ens4.rp_filter":
      "1"}}'
    reason: NodeSysctlChange
    status: "True"
    type: SysctlChanged
  - lastHeartbeatTime: "2024-07-08T21:37:27Z"
    lastTransitionTime: "2024-07-08T21:37:27Z"
    message: NodeController create implicit route
    reason: RouteCreated
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2024-07-24T23:08:37Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2024-07-24T23:08:37Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2024-07-24T23:08:37Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2024-07-24T23:08:37Z"
    lastTransitionTime: "2024-07-23T02:40:47Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
```

```
{
insertId: "1lg3pa5fgptnw6"
jsonPayload: {
apiVersion: "v1"
eventTime: null
involvedObject: {6}
kind: "Event"
lastTimestamp: "2024-07-23T02:33:56Z"
message: "Node is not ready"
metadata: {
creationTimestamp: "2024-07-23T02:33:56Z"
managedFields: [1]
name: "mirror-citus-shard0-0.17e4b6e142b590b9"
namespace: "performance-citus"
resourceVersion: "1637681"
uid: "fe8aa7b3-634e-45eb-912d-fd996f5123f3"
}
reason: "NodeNotReady"
reportingComponent: "node-controller"
reportingInstance: ""
source: {
component: "node-controller"
}
type: "Warning"
}
logName: "projects/<REDACTED>/logs/events"
receiveTimestamp: "2024-07-23T02:34:00.660878798Z"
resource: {2}
severity: "WARNING"
timestamp: "2024-07-23T02:33:56Z"
}
```

```
E0723 02:41:04.521242    1907 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/zfs.csi.openebs.io^pvc-09c95a39-cf08-4035-9f2e-2bef87ec738c podName: nodeName:}" failed. No retries permitted until 2024-07-23 02:41:20.521229794 +0000 UTC m=+33.950534160 (durationBeforeRetry 16s). Error: MountVolume.MountDevice failed for volume "pvc-09c95a39-cf08-4035-9f2e-2bef87ec738c" (UniqueName: "kubernetes.io/csi/zfs.csi.openebs.io^pvc-09c95a39-cf08-4035-9f2e-2bef87ec738c") pod "mirror-citus-shard0-0" (UID: "f3e6dda8-df2a-464a-9b77-f72225bcbd52") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name zfs.csi.openebs.io not found in the list of registered CSI drivers
MountVolume.MountDevice failed for volume "pvc-09c95a39-cf08-4035-9f2e-2bef87ec738c" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name zfs.csi.openebs.io not found in the list of registered CSI drivers
```

### Steps to reproduce

This was experienced after heavy testing in the performance environment

### Version

v.0.109.0-rc1

### Operating system

None
