### ISSUE TITLE
Struggling to run rosetta

### ISSUE THREAD

**Issue by jbaldwinroberts** [hashgraph/hedera-mirror-node#9015]
### Description

I cloned the repo, updated the application.yml file and then ran `docker compose up`.

My application.yml file contains:
```
hedera:
  mirror:
    importer:
      downloader:
        accessKey: ABC123
        cloudProvider: "s3"
        secretKey: ABC123
      network: testnet
      startDate: 2024-08-13T18:00:00Z
    monitor:
      network: testnet
    rosetta:
      network: testnet
    web3:
      evm:
        network: testnet
    rest:
      stateproof:
        streams:
          network: testnet

```

I think the importer is up to date as the logs show `2024-08-13T18:18:05.388Z  INFO scheduling-6 c.h.m.i.d.r.RecordFileDownloader No new signature files to download after file: 2024-08-13T18_18_00.716505053Z.rcd.gz. Retrying in 0.5 s`

but running  `./hedera-mirror-node/hedera-mirror-rosetta/scripts/wait-for-mirror-node.sh` results in a time out.

The rosetta logs show:
```
❯ docker compose logs -f rosetta
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:58Z" level=info msg="External configuration file not found"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:58Z" level=info msg="Using configuration: &{Cache:map[entity:{MaxSize:524288}] Db:{Host:db Name:mirror_node Password: Pool:{MaxIdleConnections:20 MaxLifetime:30 MaxOpenConnections:100} Port:5432 StatementTimeout:20 Username:mirror_rosetta} Feature:{SubNetworkIdentifier:false} Http:{IdleTimeout:10s ReadTimeout:5s ReadHeaderTimeout:3s WriteTimeout:10s} Log:{Level:info} Network:demo NodeRefreshInterval:24h0m0s NodeVersion:0 Nodes:map[] Online:true Port:5700 Realm:0 Response:{MaxTransactionsInBlock:6000} Shard:0 ShutdownTimeout:10s}"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:58Z" level=info msg="hedera-mirror-rosetta version 0.112.0-SNAPSHOT, rosetta api version 1.4.12"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:59Z" level=error msg="failed to initialize database, got error [failed to connect to `host=db user=mirror_rosetta database=mirror_node`: dial error (dial tcp 172.24.0.8:5432: connect: connection refused)]"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:59Z" level=warning msg="failed to connect to `host=db user=mirror_rosetta database=mirror_node`: dial error (dial tcp 172.24.0.8:5432: connect: connection refused)"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:02:59Z" level=info msg="Use testnet instead of demo"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:03:00Z" level=info msg="Serving Rosetta API in ONLINE mode"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:03:00Z" level=info msg="Listening on port 5700"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:03:20Z" level=info msg="172.24.0.1 POST /network/list (200) in 4.353583ms"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:03:20Z" level=info msg="172.24.0.1 POST /network/status (500) in 63.907042ms"
hedera-mirror-node-rosetta-1  | time="2024-08-13T18:03:25Z" level=info msg="172.24.0.1 POST /network/status (500) in 4.488792ms"
```

what am i doing wrong?

### Steps to reproduce

Clone the repo, update the application.yml file and then run `docker compose up`.

### Hedera network

testnet

### Version

main

### Operating system

macOS
