### ISSUE TITLE
Pre-OA Mirror Node

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#913]
**Problem**
The current Hedera Mirror Node deployments only serve data after OA. There have been customer and internal requests for pre-OA data.

**Solution**
Add a non-public pre-OA Mirror Node for mainnet to serve ad-hoc requests. This requires figuring out which buckets have the data and potentially stitching them together since there were multiple stream resets.

**Alternatives**

**Additional Context**

**Comment by xin-hedera** [comment]
The public load balancer to the rest service is at http://35.223.194.189

To grant access to customers, OPS need to add their IP address to the whitelist. This can be done by updating `spec.loadBalancerSourceRanges` of the load balancer service's yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: "2020-09-14T14:39:19Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: rest
    app.kubernetes.io/instance: hedera-mirror-node-1
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: hedera-mirror-node-1
    app.kubernetes.io/part-of: hedera-mirror-node
    app.kubernetes.io/version: 0.13.5
    helm.sh/chart: rest-0.2.3
  name: hedera-mirror-node-1-rest
  namespace: pre-oa
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: Application
    name: hedera-mirror-node-1
  selfLink: /api/v1/namespaces/pre-oa/services/hedera-mirror-node-1-rest
spec:
  clusterIP: xxx.xxx.xxx.xxx
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 70.240.247.133/32
  ports:
  - name: http
    nodePort: xxxxx
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: rest
    app.kubernetes.io/instance: hedera-mirror-node-1
    app.kubernetes.io/name: hedera-mirror-node-1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: xxx.xxx.xxx.xxx

```

**Comment by steven-sheehy** [comment]
The public load balancer to the pre-OA REST API is available upon request.

To grant access to customers, OPS need to add their IP address to the whitelist. This can be done by updating `spec.loadBalancerSourceRanges` of the load balancer service's yaml at https://console.cloud.google.com/kubernetes/service/us-central1/mirrornode-na-1/pre-oa/hedera-mirror-node-1-rest/yaml/edit?project=mirrornode.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rest
    app.kubernetes.io/instance: hedera-mirror-node-1
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: hedera-mirror-node-1
    app.kubernetes.io/part-of: hedera-mirror-node
    app.kubernetes.io/version: 0.13.5
    helm.sh/chart: rest-0.2.3
  name: hedera-mirror-node-1-rest
  namespace: pre-oa
spec:
  clusterIP: xxx.xxx.xxx.xxx
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - x.x.x.x/32
  ports:
  - name: http
    nodePort: xxxxx
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: rest
    app.kubernetes.io/instance: hedera-mirror-node-1
    app.kubernetes.io/name: hedera-mirror-node-1
  sessionAffinity: None
  type: LoadBalancer
```
